# Generated by Django 5.2.3 on 2025-10-06 15:46

import authentification.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telephone', models.CharField(max_length=20)),
                ('code_otp', models.CharField(default=authentification.models.generate_otp, max_length=6)),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('est_verifie', models.BooleanField(default=False)),
            ],
        ),
    ]
