# Generated by Django 5.2.3 on 2025-09-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='prenoms_utlisateur',
            new_name='prenoms_utilisateur',
        ),
    ]
