# Generated by Django 5.2.3 on 2025-09-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_rename_prenoms_utlisateur_utilisateur_prenoms_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='nom_utilisateur',
            field=models.CharField(max_length=50, verbose_name='Entrez votre nom'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenoms_utilisateur',
            field=models.CharField(max_length=200, verbose_name='Entrez votre prenoms'),
        ),
    ]
