# Generated by Django 5.2.3 on 2025-09-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_utilisateur_nom_utilisateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_utilisateur',
            field=models.ImageField(blank=True, null=True, upload_to='photo_profil_utilisateur/'),
        ),
    ]
