# Generated by Django 5.2.3 on 2025-09-27 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_utilisateur_is_staff_alter_utilisateur_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom_utilisateur',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='numero_tel_utilisateur',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format : '+2250700000000' (jusqu'à 15 chiffres).", regex='^\\+?1?\\d{9,15}$')], verbose_name='Numero de téléphone'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_utilisateur',
            field=models.ImageField(blank=True, null=True, upload_to='photo_profil_utilisateur/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenoms_utilisateur',
            field=models.CharField(max_length=200, verbose_name='Prenoms'),
        ),
    ]
