# Generated by Django 5.2.3 on 2025-09-28 01:22

import utilisateurs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_alter_utilisateur_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_utilisateur',
            field=models.ImageField(blank=True, default=utilisateurs.models.photo_profil_par_defaut, null=True, upload_to='photo_profil_utilisateur/', verbose_name='Photo de profil'),
        ),
    ]
