# Generated by Django 5.2.3 on 2025-10-06 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_alter_utilisateur_photo_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='nom_utilisateur',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='numero_tel_utilisateur',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format : '+2250700000000' (jusqu'à 15 chiffres).", regex='^\\+?1?\\d{9,15}$')], verbose_name='Numero de téléphone'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenoms_utilisateur',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Prenoms'),
        ),
    ]
