# Generated by Django 5.2.3 on 2025-10-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_alter_utilisateur_nom_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='provider',
            field=models.CharField(default='local', max_length=50),
        ),
    ]
