# Generated by Django 5.2.3 on 2025-10-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0010_alter_utilisateur_numero_tel_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Adresse Email'),
        ),
    ]
