# Generated by Django 5.2.3 on 2025-10-06 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0011_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='numero_tel_utilisateur',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format : '+2250700000000' (jusqu'à 15 chiffres).", regex='^\\+?1?\\d{8,15}$')], verbose_name='Numero de téléphone'),
        ),
    ]
